#!/usr/bin/env bash

set -o errexit
set -o pipefail
TIMEFORMAT="Task completed in %3lR"
BIN="./.venv/bin"

function help {
    echo "Options:"
    echo "    check:    Formatting checks"
    echo "    clean:    Clean all build and test directories, as well as extraneous artificats"
    echo "    cov: Run tests with code coverage"
    echo "    docs:     Build the documentation"
    echo "    format:   Run formatter"
    echo "    init:     Setup dev environment"
    echo "    lint:     Linter"
    echo "    test:     Execute tests"
}

function init {
    python3 -m venv --prompt sw venv
    "${BIN}/python" -m pip install -e ".[dev,test,docs]"
}

function lint {
    "${BIN}/ruff" check swingtime demo tests
}

function check {
    "${BIN}/ruff" format --check swingtime demo tests
}

function format {
    "${BIN}/ruff" format swingtime demo tests
}

function test {
    "${BIN}/pytest" -s tests "$@"

}

function cov {
    "${BIN}/pytest" --cov-report html --cov-report term --cov=swingtime
}

function clean {
    find . -type f -name "*.pyc" -delete
    find . -type d -name "__pycache__" -delete
    rm -f demo/karate.db .coverage
    rm -rf \
        .tox \
        .pytest_cache \
        build \
        django_swingtime.egg-info \
        dist

}

function docs {
    pushd docs
    make html
    popd
}

if [ -z "$1" ]; then
    help
else
    what=$1
    shift
    time ${what:-help} "$@"
fi
