# Generated by Django 4.2.23 on 2025-07-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="title")),
                ("description", models.CharField(max_length=100, verbose_name="description")),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("abbr", models.CharField(max_length=4, unique=True, verbose_name="abbreviation")),
                ("label", models.CharField(max_length=50, verbose_name="label")),
            ],
            options={
                "verbose_name": "event type",
                "verbose_name_plural": "event types",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(verbose_name="end time")),
                (
                    "event",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karate.event",
                    ),
                ),
            ],
            options={
                "ordering": ("start_time", "end_time"),
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="karate.eventtype"
            ),
        ),
    ]
