#!/bin/bash
PYWARN='python -Wd'
pip install -r requirements.txt
cd ../docs
make html
cd -
VER=$(python manage.py --version)
$PYWARN manage.py loaddemo
$PYWARN manage.py collectstatic --noinput --link
if [[ "$VER" > "1.6" ]]
then
    $PYWARN manage.py check
fi

$PYWARN manage.py runserver

