#!/bin/bash
PYWARN='python -Wd'
pip install -r ../requirements.txt
cd ../docs
make html
cd -
$PYWARN manage.py check
$PYWARN manage.py loaddemo
#$PYWARN manage.py collectstatic --noinput --link
$PYWARN manage.py runserver

