#!/bin/bash

PYWARN='python -Wd'

function run_tests {
    $PYWARN manage.py test swingtime
    $PYWARN manage.py loaddemo
}

pip install -r requirements.txt

$PYWARN manage.py check
run_tests

pip uninstall --yes django
pip install "django<1.7"
run_tests

pip uninstall --yes django
pip install "django<1.6"
run_tests
